#!/bin/bash
#PBS -q b534  
#PBS -l nodes=i96:ppn=8+i97:ppn=8
#PBS -l walltime=01:00:00
#PBS -o group09_switch$PBS_JOBID.out

PAGERANK=/N/u/jiang28/Project4/MPI_pagerank/mpi_main
PROQUERY=mpi_main
MONITORDIR=/N/u/jiang28/Project4/MonitorDaemon/
DATADIR=/N/u/jiang28/Project4_Data/
DATAFILE=${DATADIR}project3_1M
OUTDIR=/N/u/jiang28/Project4_Result/
OUTURLS=${OUTDIR}topurls.txt
OUTLOG=${OUTDIR}bmlog.txt
NODEFILE=${OUTDIR}bmnodes
BROKERIP=129.79.49.248
BROKERPORT=61616
PRONUM=8
ITERNUM=100
THRESH=-0.001

#================================================BM==================================================
cat $PBS_NODEFILE
uniq $PBS_NODEFILE > ${NODEFILE}
# run the MPI pagerank and monitoring application in Bare Metal Cluster
# ========= 
module load openmpi
#mpirun -hostfile ${PBS_NODEFILE} -np ${PRONUM} ${PAGERANK} -i ${DATAFILE} -o ${OUTURLS} -n ${ITERNUM} -t ${THRESH} > ${OUTLOG} 2>&1 &
mpirun -hostfile ${NODEFILE} -np ${PRONUM} ${PAGERANK} ${DATAFILE} ${OUTURLS} ${ITERNUM} ${THRESH} ${OUTLOG} &

sleep 1
for NODE in `uniq $PBS_NODEFILE`
do
	ssh $NODE "cd ${MONITORDIR}; java -cp \"./lib/*:.\" project3/ProcCpuMem ${BROKERIP} ${BROKERPORT} ${PROQUERY}" &
done
wait
# =========
echo "Bare Metal job Finished"

# =================================================VM==================================================
sleep 1

# Note that we are actually sourcing (. Script) the following script to make/get the environment variables. otherwise you won’t get the $VM_NODEFILE
# environmental variable.

#DATAFILE=${DATADIR}project3-1M
OUTLOG=${OUTDIR}vmlog.txt
NODEFILE=${OUTDIR}vminstances
ITERNUM=100

. /usr/local/bin/start_vms

echo "Waiting for the VM's to be reachable"
. /usr/local/bin/wait_for_vms $VM_NODEFILE
cat $VM_NODEFILE

# If you want to access the VM_NODEFILE from a shell script you first have to export it as a different 
# environmental variable.
export NODES=$VM_NODEFILE
cat $NODES
# (start your MPJ daemons and) run the MPI/MPJPagerank and monitoring applicationin VM's
# ========= 

VMIP=`cat $NODES | sed -n 1p`
echo $VMIP
#module load openmpi
cat $NODES | sort -u > ${NODEFILE}
ssh $VMIP "mpirun --mca btl_tcp_if_exclude lo,eth1 --hostfile ${NODEFILE} -np ${PRONUM} ${PAGERANK} -i ${DATAFILE} -o ${OUTURLS} -n ${ITERNUM} -t ${THRESH} > ${OUTLOG} 2>&1" &
sleep 1
for NODE in `cat ${NODEFILE}`
do
        ssh $NODE "cd ${MONITORDIR}; /N/u/jiang28/bin/jdk1.6.0_31/bin/java -cp \"./lib/*:.\" project3/ProcCpuMem ${BROKERIP} ${BROKERPORT} ${PROQUERY}" &
done
wait
# =========
echo "shutting down VM's"
. /usr/local/bin/shutdown_vms
echo "VM Job finished"
